spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id : getPatients
          uri: http://localhost:8081/
          predicates:
            - Path= /patients/**
server:
  port: 8888