spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id : patients
          uri: http://localhost:8081/
          predicates:
            - Path= /patients/**
        - id: notes
          uri: http://localhost:8082/
          predicates:
            - Path= /notes/**
server:
  port: 8888