spring:
  cloud:
    gateway:
      routes:
        - id : getPatients
          uri: http://localhost:8081/
          predicates:
            - Path= /patients
        - id: getPatient
          uri: http://localhost:8081/
          predicates:
            - Path= /patient/**
        - id: updatePatient
          uri: http://localhost:8081/
          predicates:
            - Path= /updatePatient/**
server:
  port: 8888