spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id : patients
          uri: http://localhost:8081/
          predicates:
            - Path= /patients/**
        - id: notes
          uri: http://localhost:8082/
          predicates:
            - Path= /notes/**
        - id: assessment
          uri: http://localhost:8083/
          predicates:
            - Path= /assessment/**
server:
  port: 8888

user:
  username: user
  password: 3f8ea724-380d-4cef-85e2-34f6297f0fec