services:
  patient-service-db:
    image: postgres
    container_name: patient-service-db
    env_file:
      - ./patientService/.env.docker
    environment:
      POSTGRES_DB: patient-service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3

  patient-service:
    build: ./patientService
    container_name: patient-service
    env_file:
      - ./patientService/.env.docker
    depends_on:
      patient-service-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5

  note-service-db:
    image: mongo
    container_name: note-service-db
    command: mongod --auth
    env_file:
      - ./noteService/.env.docker
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/note-service --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  note-service:
    build: ./noteService
    container_name: note-service
    env_file:
      - ./noteService/.env.docker
    depends_on:
      note-service-db:
        condition: service_healthy

  gateway-service:
    build: ./gatewayService
    container_name: gateway-service
    env_file:
      - ./gatewayService/.env.docker
    depends_on:
      patient-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5

  assessment-service:
    build: ./assessmentService
    container_name: assessment-service
    env_file:
      - ./assessmentService/.env.docker
    depends_on:
      gateway-service:
        condition: service_healthy

  client-service:
    build: ./clientService
    container_name: client-service
    env_file:
      - ./clientService/.env.docker
    depends_on:
      gateway-service:
        condition: service_healthy
    ports:
      - '8080:8080'
    expose:
      - '8080'