services:
  patient-service:
    build: ./patientService
    container_name: patient-service
    env_file:
      - ./.env.docker
    ports:
      - '8081:8081'
    expose:
      - '8081'
    depends_on:
      - patient-service-db

  patient-service-db:
    image: postgres
    container_name: patient-service-db
    env_file:
      - ./.env.docker
    environment:
      POSTGRES_DB: patient-service

  note-service:
    build: ./noteService
    container_name: note-service
    env_file:
      - ./.env.docker
    ports:
      - '8082:8082'
    expose:
      - '8082'
    depends_on:
      - note-service-db

  note-service-db:
    image: mongo
    container_name: note-service-db
    command: mongod --auth
    env_file:
      - ./.env.docker
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  gateway-service:
    build: ./gatewayService
    container_name: gateway-service
    env_file:
      - ./.env.docker
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      - note-service
      - patient-service