services:
  patient-service:
    build: ./patientService
    container_name: patient-service
    env_file:
      - ./.env.docker
    ports:
      - '8081:8081'
    expose:
      - '8081'
    depends_on:
      - patient-service-db

  patient-service-db:
    image: postgres
    container_name: patient-service-db
    env_file:
      - ./.env.docker
    environment:
      POSTGRES_DB: patient-service